homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles

# Enables the frontend
frontend:

lovelace:
  mode: yaml

# Enables configuration UI
config:

http:

python_script:

cast_volume_tracker: !include cast_volume_trackers.yaml
input_number: !include input_numbers.yaml
script: !include_dir_merge_named scripts/
switch: !include switches.yaml
